### ISSUE TITLE
Не накладывайте полупрозрачные слои на автопроигрываемое видео

### ISSUE THREAD

**Issue by MikeSha** [nicothin/web-design#22]
> Не накладывайте полупрозрачные слои на автопроигрываемое видео

Не могли бы вы дать ссылку, где об этом почитать подробнее? У нас тут небольшой спор с коллегами.

**Comment by nicothin** [comment]
увы, пруфов нет (неплохая тема для статьи-исследования)
это я добавил, кажется, после наблюдения за тормозами на не самом слабом устройстве.
причем после убирания наложения тормозов было меньше.

**Comment by MikeSha** [comment]
Спасибо большое

**Comment by nicothin** [comment]
совершенно не за что, на самом деле :(
