### ISSUE TITLE
Про капс в заголовках!)

### ISSUE THREAD

**Issue by ademaro** [nicothin/web-design#6]

**Comment by nicothin** [comment]
что по капс в заголовках?
технологически серьезной разницы не чувствую.

**Comment by izlom** [comment]
«**ВСЕГДА** думайте о…»
Быть может речь про это? =)

**Comment by nicothin** [comment]
Хм. 
Не нравится способ акцентировки слов? Ну сменил на более приятный глазу. :)

**Comment by ademaro** [comment]
Писал с телефона очень кратко, что бы не забыть) 

Я имел в виду, что многие дизайнеры любят писать капсом в заголовках, что не есть хорошо. При копипасте из псд — приходится ещё кликать пару раз, что бы привести текст в нормальное состояние. В фотошопе же есть пункт "All caps", который захочется при вёрстке сделать через text-transform: uppercase, а не оставлять просто капсом...

**Comment by nicothin** [comment]
добавил в «неприятные мелочи»
